const obj = {
  Command: [
    "Open a new window",
    "Open a new window in Incognito mode",
    "Open a new tab, and jump to it",
    "Reopen previously closed tabs in the order they were closed",
    "Jump to the next open tab",
    "Jump to the previous open tab",
    "Jump to a specific tab",
    "Jump to the rightmost tab",
    "Open your home page in the current tab",
    "Open the previous page from your browsing history in the current tab",
    "Open the next page from your browsing history in the current tab",
    "Close the current tab",
    "Close the current window",
    "Minimize the current window",
    "Maximize the current window",
    "Quit Google Chrome",
    "",
    "Action",
    "Open the Chrome menu",
    "Show or hide the Bookmarks bar",
    "Open the Bookmarks Manager",
    "Open the History page in a new tab",
    "Open the Downloads page in a new tab",
    "Open the Chrome Task Manager",
    "Set focus on the first item in the Chrome toolbar",
    "Set focus on the rightmost item in the Chrome toolbar",
    "Switch focus to unfocused dialog (if showing) and all toolbars",
    "Open the Find Bar to search the current page",
    "Jump to the next match to your Find Bar search",
    "Jump to the previous match to your Find Bar search",
    "Open Developer Tools",
    "Open the Clear Browsing Data options",
    "Open the Chrome Help Center in a new tab",
    "Log in a different user or browse as a Guest",
    "Open a feedback form",
    "Turn on caret browsing",
    "Skip to web contents",
    "Focus on inactive dialogs",
    "Action",
    "Search with your default search engine",
    "Search using a different search engine",
    "Add www. and .com to a site name, and open it in the current tab",
    "Add www. and .com to a site name, and open it in a new window",
    "Open a new tab and perform a Google search",
    "Jump to the address bar",
    "Search from anywhere on the page",
    "Remove predictions from your address bar",
    "Move cursor to the address bar",
    "Action",
    "Open options to print the current page",
    "Open options to save the current page",
    "Reload the current page",
    "Reload the current page, ignoring cached content",
    "Stop the page loading",
    "Browse clickable items moving forward",
    "Browse clickable items moving backward",
    "Open a file from your computer in Chrome",
    "Display non-editable HTML source code for the current page",
    "Save your current webpage as a bookmark",
    "Save all open tabs as bookmarks in a new folder",
    "Turn full-screen mode on or off",
    "Make everything on the page bigger",
    "Make everything on the page smaller",
    "Return everything on the page to default size",
    "Scroll down a webpage, a screen at a time",
    "Scroll up a webpage, a screen at a time",
    "Go to the top of the page",
    "Go to the bottom of the page",
    "Scroll horizontally on the page",
    "Move your cursor to the beginning of the previous word in a text field",
    "Move your cursor to the next word",
    "Delete the previous word in a text field",
    "Open the Home page in the current tab",
    "Action",
    "Open a link in a current tab (mouse only)",
    "Open a link in new background tab",
    "Open a link, and jump to it",
    "Open a link, and jump to it (mouse only)",
    "Open a link in a new window",
    "Open a tab in a new window (mouse only)",
    "Move a tab to a current window (mouse only)",
    "Return a tab to its original position",
    "Save the current webpage as a bookmark",
    "Scroll horizontally on the page",
    "Download the target of a link",
    "Display your browsing history",
    "Switch between maximized and windowed modes",
    "Make everything on the page bigger",
    "Make everything on the page smaller",
    "Action",
    "Open a new window",
    "Open a new window in Incognito mode",
    "Open a new tab, and jump to it",
    "Reopen previously closed tabs in the order they were closed",
    "Jump to the next open tab",
    "Jump to the previous open tab",
    "Jump to a specific tab",
    "Jump to the last tab",
    "Open the previous page in your browsing history for the current tab",
    "Open the next page in your browsing history for the current tab",
    "Close the current tab or pop-up",
    "Close the current window",
    "Minimize the window",
    "Hide Google Chrome",
    "Quit Google Chrome",
    "",
    "Action",
    "Show or hide the Bookmarks Bar",
    "Open the Bookmark Manager",
    "Open the Settings page in a new tab",
    "Open the History page in a new tab",
    "Open the Downloads page in a new tab",
    "Open the Find Bar to search the current page",
    "Jump to the next match to your Find Bar search",
    "Jump to the previous match to your Find Bar search",
    "When Find Bar is open, search for selected text",
    "Open Developer Tools",
    "Open the Clear Browsing Data options",
    "Log in as a different user, browse as a Guest, or access payment and password info",
    "Jump to the main menu bar",
    "Cycle focus to unfocused dialog (if showing) and all toolbars",
    "Open a feedback form",
    "Turn on caret browsing",
    "Focus on inactive dialogs",
    "Action",
    "Search with your default search engine",
    "Search using a different search engine",
    "Add www. and .com to a site name, and open it in the current tab",
    "Add www. and .com to a site name, and open it in a new window",
    "Open the website in a new background tab",
    "Jump to the address bar",
    "Remove predictions from your address bar",
    "Move cursor to the address bar",
    "Action",
    "Compose a new email message with a link to the current page",
    "Open options to print the current page",
    "Open options to save the current page",
    "Open the Page Setup dialog",
    "Reload your current page, ignoring cached content",
    "Stop the page loading",
    "Browse clickable items moving forward",
    "Browse clickable items moving backward",
    "Open a file from your computer in Google Chrome",
    "Display non-editable HTML source code for the current page",
    "Open the JavaScript Console",
    "Save your current webpage as a bookmark",
    "Save all open tabs as bookmarks in a new folder",
    "Turn full-screen mode on or off",
    "Make everything on the page bigger",
    "Make everything on the page smaller",
    "Return everything on the page to the default size",
    "Scroll down a webpage, a screen at a time",
    "Scroll up a webpage, a screen at a time",
    "Search the web",
    "Move your cursor to the beginning of the previous word in a text field",
    "Move your cursor to the back of the next word in a text field",
    "Delete the previous word in a text field",
    "Open your home page in the current tab",
    "Action",
    "Open a link in a current tab (mouse only)",
    "Open a link in new background tab",
    "Open a link, and jump to it",
    "Open a link, and jump to it (mouse only)",
    "Open a link in a new window",
    "Open a tab in a new window (mouse only)",
    "Move a tab to a current window (mouse only)",
    "Return a tab to its original position",
    "Save the current webpage as a bookmark",
    "Download the target of a link",
    "Display your browsing history",
    "Increase the window to full height",
  ],
  Hotkey: [
    "Ctrl + n",
    "Ctrl + Shift + n",
    "Ctrl + t",
    "Ctrl + Shift + t",
    "Ctrl + Tab or Ctrl + PgDn",
    "Ctrl + Shift + Tab or Ctrl + PgUp",
    "Ctrl + 1 through Ctrl + 8",
    "Ctrl + 9",
    "Alt + Home",
    "Alt + Left arrow",
    "Alt + Right arrow",
    "Ctrl + w or Ctrl + F4",
    "Ctrl + Shift + w or\u00a0Alt + F4",
    "Alt + Space then n",
    "Alt + Space then\u00a0x",
    "Alt + f then x",
    "Move tabs right or left",
    "Shortcut",
    "Alt + f or Alt + e",
    "Ctrl + Shift + b",
    "Ctrl + Shift + o",
    "Ctrl + h",
    "Ctrl + j",
    "Shift + Esc",
    "Shift + Alt + t",
    "F10\u00a0",
    "F6",
    "Ctrl + f or F3",
    "Ctrl + g",
    "Ctrl + Shift + g",
    "Ctrl + Shift + j\u00a0or F12",
    "Ctrl + Shift + Delete",
    "F1",
    "Ctrl + Shift + m",
    "Alt + Shift + i",
    "F7",
    "Ctrl + F6",
    "Alt + Shift + a",
    "Shortcut",
    "Type a search term +\u00a0Enter",
    "Type a search engine name and press\u00a0Tab",
    "Type a site name +\u00a0Ctrl + Enter",
    "Type a site name +\u00a0Ctrl + Shift + Enter",
    "Type a search term +\u00a0Alt + Enter",
    "Ctrl + l or Alt + d or F6",
    "Ctrl + k or Ctrl + e",
    "Down arrow\u00a0to highlight +\u00a0Shift + Delete",
    "Ctrl + F5",
    "Shortcut",
    "Ctrl + p",
    "Ctrl + s",
    "F5 or Ctrl + r",
    "Shift + F5 or Ctrl + Shift + r",
    "Esc",
    "Tab",
    "Shift + Tab",
    "Ctrl + o + Select a file",
    "Ctrl + u",
    "Ctrl + d",
    "Ctrl + Shift + d",
    "F11",
    "Ctrl and +",
    "Ctrl and -",
    "Ctrl + 0",
    "Space or PgDn",
    "Shift + Space or PgUp",
    "Home",
    "End",
    "Shift + Scroll your mousewheel",
    "Ctrl + Left arrow",
    "Ctrl + Right arrow",
    "Ctrl + Backspace",
    "Alt + Home",
    "Shortcut",
    "Drag a link to a tab",
    "Ctrl +\u00a0Click a link",
    "Ctrl + Shift +\u00a0Click a link",
    "Drag a link to a blank area of the tab strip",
    "Shift +\u00a0Click a link",
    "Drag the tab out of the tab strip",
    "Drag the tab into an existing window",
    "Press Esc while dragging",
    "Drag the web address to the Bookmarks Bar",
    "Shift + Scroll your mousewheel",
    "Alt +\u00a0Click a link",
    "",
    "Double-click a blank area of the tab strip",
    "Ctrl + Scroll your mousewheel up",
    "Ctrl + Scroll your mousewheel down",
    "Shortcut",
    "\u2318 + n",
    "\u2318 + Shift + n",
    "\u2318 + t",
    "\u2318 + Shift + t",
    "\u2318 + Option + Right arrow",
    "\u2318 + Option + Left arrow",
    "\u2318 + 1 through \u2318 + 8",
    "\u2318 + 9",
    "\u2318 + [ or \u2318 + Left arrow",
    "\u2318 + ] or \u2318 + Right arrow",
    "\u2318 + w",
    "\u2318 + Shift + w",
    "\u2318 + m",
    "\u2318 + h",
    "\u2318 + q",
    "Move tabs right or left",
    "Shortcut",
    "\u2318 + Shift + b",
    "\u2318 + Option + b",
    "\u2318 + ,",
    "\u2318 + y",
    "\u2318 + Shift + j",
    "\u2318 + f",
    "\u2318 + g",
    "\u2318 + Shift + g",
    "\u2318 + e",
    "\u2318 + Option + i",
    "\u2318 + Shift + Delete",
    "\u2318 + Shift + m",
    "Control + F2",
    "\u2318 + Option + Up arrow or Down arrow",
    "\u2318 + Option + Shift + i",
    "F7",
    "\u2318 + Option + Shift + a",
    "Shortcut",
    "Type a search term + Return",
    "Type a search engine name and press\u00a0Tab",
    "Type a site name\u00a0+\u00a0Ctrl + Return",
    "Type a site name +\u00a0Ctrl + Shift + Return",
    "Type a web address +\u00a0\u2318 + Return",
    "\u2318 + l",
    "",
    "Ctrl + F5",
    "Shortcut",
    "\u2318 + Shift + i",
    "\u2318 + p",
    "\u2318 + s",
    "\u2318 + Option + p",
    "\u2318 + Shift + r",
    "Esc",
    "Tab",
    "Shift + Tab",
    "\u2318 + o + Select a file",
    "\u2318 + Option + u",
    "\u2318 + Option + j",
    "\u2318 + d",
    "\u2318 + Shift + d",
    "\u2318 + Ctrl + f",
    "\u2318 and +",
    "\u2318 and -",
    "\u2318 + 0",
    "Space",
    "Shift + Space",
    "\u2318 + Option + f",
    "Option + Left arrow",
    "Option + Right arrow",
    "Option + Delete",
    "\u2318 + Shift + h",
    "Shortcut",
    "Drag a link to a tab",
    "\u2318 +\u00a0Click a link",
    "\u2318 + Shift +\u00a0Click a link",
    "Drag a link to a blank area of the tab strip",
    "Shift +\u00a0Click a link",
    "Drag the tab out of the tab strip",
    "Drag the tab into an existing window",
    "Press Esc while dragging",
    "Drag the web address to the Bookmarks Bar",
    "Option +\u00a0Click a link",
    "",
    "Double-click a blank area of the tab strip",
  ],
};

const response = JSON.stringify(obj);
